<div class="footer-sub">
    <ul class="footer-sub-list">
        <li><a href="#">about us</a></li>
        <li><a href="#">blog</a></li>
        <li><a href="#">faqs</a></li>
        <li><a href="#">order tracking</a></li>
        <li><a href="#">contact</a></li>
    </ul>
    <div class="footer-sub-social">
        <span>connect with us:</span>
        <ul>
            <li>
                <a class="behance fa fa-behance" href="#">
                </a>
            </li>
            <li>
                <a class="behance fa fa-facebook" href="#">
                </a>
            </li>
            <li>
                <a class="behance fa fa-google" href="#">
                </a>
            </li>
            <li>
                <a class="behance fa fa-skype" href="#">
                </a>
            </li>
            <li>
                <a class="behance fa fa-twitter" href="#">
                </a>
            </li>
        </ul>
    </div>
</div>
